// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnthhFp5TiZ6wanNUsniNMl2HfUSu5m-I',
    appId: '1:604400657999:web:40b108502f8ae0905aec3a',
    messagingSenderId: '604400657999',
    projectId: 'checklistapp-26057',
    authDomain: 'checklistapp-26057.firebaseapp.com',
    storageBucket: 'checklistapp-26057.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NrJdACufgqoPK0CkLNN5cruMbdEcqT8',
    appId: '1:604400657999:android:3fcecae22ed352f25aec3a',
    messagingSenderId: '604400657999',
    projectId: 'checklistapp-26057',
    storageBucket: 'checklistapp-26057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQN4kO_0gBfLdR4C-EH8MdmjWreF4_u5I',
    appId: '1:604400657999:ios:6645091f063c35565aec3a',
    messagingSenderId: '604400657999',
    projectId: 'checklistapp-26057',
    storageBucket: 'checklistapp-26057.firebasestorage.app',
    iosBundleId: 'com.example.checklistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQN4kO_0gBfLdR4C-EH8MdmjWreF4_u5I',
    appId: '1:604400657999:ios:6645091f063c35565aec3a',
    messagingSenderId: '604400657999',
    projectId: 'checklistapp-26057',
    storageBucket: 'checklistapp-26057.firebasestorage.app',
    iosBundleId: 'com.example.checklistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnthhFp5TiZ6wanNUsniNMl2HfUSu5m-I',
    appId: '1:604400657999:web:df056d7309966b3a5aec3a',
    messagingSenderId: '604400657999',
    projectId: 'checklistapp-26057',
    authDomain: 'checklistapp-26057.firebaseapp.com',
    storageBucket: 'checklistapp-26057.firebasestorage.app',
  );
}
