import 'package:checklist_app/core/theme/app_colors.dart';
import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.primary,
  onPrimary: Colors.white,
  primaryContainer: AppColors.primaryContainer,
  onPrimaryContainer: AppColors.primaryDark,
  secondary: AppColors.accent,
  onSecondary: Colors.white,
  secondaryContainer: AppColors.primaryContainer,
  onSecondaryContainer: AppColors.primaryDark,
  tertiary: AppColors.successLight,
  onTertiary: Colors.white,
  tertiaryContainer: AppColors.primaryContainer,
  onTertiaryContainer: AppColors.primaryDark,
  error: AppColors.errorLight,
  onError: Colors.white,
  errorContainer: Color(0xFFFEE2E2),
  onErrorContainer: Color(0xFF7F1D1D),
  surface: AppColors.surfaceLight,
  onSurface: AppColors.textPrimaryLight,
  onSurfaceVariant: AppColors.textSecondaryLight,
  outline: AppColors.borderLight,
  outlineVariant: AppColors.dividerLight,
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: AppColors.surface,
  onInverseSurface: Colors.white,
  inversePrimary: AppColors.primaryLight,
  surfaceTint: AppColors.primary,
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primaryLight,
  onPrimary: Colors.white,
  primaryContainer:  AppColors.primaryContainerDark,                                              //AppColors.primaryDark,
  onPrimaryContainer: AppColors.primaryContainer,
  secondary: AppColors.accent,
  onSecondary: Colors.black,
  secondaryContainer: AppColors.primaryDark,
  onSecondaryContainer: AppColors.primaryContainer,
  tertiary: AppColors.success,
  onTertiary: Colors.black,
  tertiaryContainer: AppColors.primaryDark,
  onTertiaryContainer: AppColors.primaryContainer,
  error: AppColors.error,
  onError: Colors.white,
  errorContainer: Color(0xFF4A1E1E),
  onErrorContainer: Color(0xFFFFCDD2),
  surface: AppColors.surface,
  onSurface: Colors.white,
  onSurfaceVariant: AppColors.textSecondary,
  outline: AppColors.border,
  outlineVariant: AppColors.divider,
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: AppColors.surfaceLight,
  onInverseSurface: AppColors.textPrimaryLight,
  inversePrimary: AppColors.primary,
  surfaceTint: Colors.transparent,
  surfaceContainerLowest: AppColors.surfaceSubtle,
  surfaceContainerLow: AppColors.surface,
  surfaceContainer: AppColors.surfaceAlt,
  surfaceContainerHigh: AppColors.surfaceStrong,
  surfaceContainerHighest: AppColors.border,
);